// app/layout.tsx
import "./globals.css";
import { Metadata } from "next";
import ClientWrapper from "./ClientWrapper";

export const metadata: Metadata = {
  title: "Moodz Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{/* Add suppressHydrationWarning here */}
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
